---
title: "Plotly Examples"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

My name is Ziyang and I am making _websit of graphic plot_!


```{r}
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```



## Let's make some plots

```{r}
data(nyc_airbnb)
```

```{r}
set.seed(1)

nyc_airbnb = #一些初步的数据处理
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)  %>% #price在100到500之间
  sample_n(5000) 
```

```{r}
nyc_airbnb %>% 
  plot_ly(x = ~lat, y = ~long, type = "scatter", mode = "markers") #plot_ly的编写格式和ggplot不太一样
#用plot_ly制作的图片,每一个点的x和y值都能看到(很吊)

nyc_airbnb %>% 
  plot_ly(x = ~lat, y = ~long, type = "scatter", mode = "markers", color = ~price, alpha = 0.5)#加颜色
```

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2") #用plot_ly做出来的box plot我们可以看到每个box的quantile,median,max,min(很吊)
```

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% #在做bar chart之前我们要自己生成bar chart的值(在这里是neighbourhood出现的次数)
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% #让它们按照次数重新排序
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```

